### ISSUE TITLE
Document append-path and prepend-ld-library-path that app needs to set in readme

### ISSUE THREAD

**Issue by bbhtt** [flathub/org.freedesktop.Sdk.Extension.swift6#3]
Like https://github.com/flathub/org.freedesktop.Sdk.Extension.llvm17/?tab=readme-ov-file#build

**Comment by bbhtt** [comment]
Same thing should be documented for swift 5 too.

**Comment by david-swift** [comment]
Thanks! This will be implemented in #4 and https://github.com/flathub/org.freedesktop.Sdk.Extension.swift5/pull/5.
